// eslint-disable-next-line
export default {
  SetUnderflow: {
    SET_UNDERFLOW: "SET_UNDERFLOW",
  },
  SetInternalError: {
    SET_INTERNAL_ERROR: "SET_INTERNAL_ERROR",
  },
  SetInvalidParams: {
    SET_INVALID_PARAMS: "SET_INVALID_PARAMS",
  },
  ClearFlags: {
    CLEAR_FLAGS_REQUEST: "CLEAR_FLAGS_REQUEST",
  },
  Transactions: {
    GET_PENDING_TRANSACTIONS_REQUEST: "GET_PENDING_TRANSACTIONS_REQUEST",
    GET_PENDING_TRANSACTIONS_SUCCESS: "GET_PENDING_TRANSACTIONS_SUCCESS",
    GET_PENDING_TRANSACTIONS_FAIL: "GET_PENDING_TRANSACTIONS_FAIL",
  },
  Clear: {
    CLEAR_REQUEST: "CLEAR_REQUEST",
  },
  ClearBalance: {
    CLEAR_BALANCE: "CLEAR_BALANCE",
  },
  Interface: {
    ADDRESS_COPIED: "ADDRESS_COPIED",
    ADDRESS_UNCOPIED: "ADDRESS_UNCOPIED",
  },
  SetReceiver: {
    SET_RECEIVER: "SET_RECEIVER",
  },
  SetRejected: {
    SET_REJECTED: "SET_REJECTED",
  },
  SetContracts: {
    SET_CONTRACTS_REQUEST: "SET_CONTRACTS_REQUEST",
    SET_CONTRACTS_SUCCESS: "SET_CONTRACTS_SUCCESS",
    SET_CONTRACTS_FAIL: "SET_CONTRACTS_FAIL",
    SET_CONTRACTS_PENDING: "SET_CONTRACTS_PENDING",
  },
  Balances: {
    BALANCES_REQUEST: "BALANCES_REQUEST",
    BALANCES_SUCCESS: "BALANCES_SUCCESS",
    BALANCES_FAIL: "BALANCES_FAIL",
    BALANCES_PENDING: "BALANCES_PENDING",
  },
  SetWalletAddress: {
    SET_WALLET_ADDRESS_REQUEST: "SET_WALLET_ADDRESS_REQUEST",
    SET_WALLET_ADDRESS_SUCCESS: "SET_WALLET_ADDRESS_SUCCESS",
    SET_WALLET_ADDRESS_FAIL: "SET_WALLET_ADDRESS_FAIL",
    SET_WALLET_ADDRESS_PENDING: "SET_WALLET_ADDRESS_PENDING",
  },
  SetWalletConnected: {
    SET_WALLET_CONNECTED_REQUEST: "SET_WALLET_CONNECTED_REQUEST",
    SET_WALLET_CONNECTED_SUCCESS: "SET_WALLET_CONNECTED_SUCCESS",
    SET_WALLET_CONNECTED_FAIL: "SET_WALLET_CONNECTED_FAIL",
    SET_WALLET_CONNECTED_PENDING: "SET_WALLET_CONNECTED_PENDING",
  },
  SetChainId: {
    SET_CHAIN_ID: "SET_CHAIN_ID",
    SET_CHAIN_ID_REQUEST: "SET_CHAIN_ID_REQUEST",
    SET_CHAIN_ID_SUCCESS: "SET_CHAIN_ID_SUCCESS",
    SET_CHAIN_ID_FAIL: "SET_CHAIN_ID_FAIL",
    SET_CHAIN_ID_PENDING: "SET_CHAIN_ID_PENDING",
  },
  SetProvider: {
    SET_PROVIDER_REQUEST: "SET_PROVIDER_REQUEST",
    SET_PROVIDER_SUCCESS: "SET_PROVIDER_SUCCESS",
    SET_PROVIDER_FAIL: "SET_PROVIDER_FAIL",
    SET_PROVIDER_PENDING: "SET_PROVIDER_PENDING",
  },
  Conversions: {
    LOAD_CONVERSION_REQUEST: "LOAD_CONVERSION_REQUEST",
    LOAD_CONVERSION_SUCCESS: "LOAD_CONVERSION_SUCCESS",
    LOAD_CONVERSION_FAIL: "LOAD_CONVERSION_FAIL",
    LOAD_CONVERSION_PENDING: "LOAD_CONVERSION_PENDING",
  },
  MintApprove: {
    MINT_APPROVE_REQUEST: "MINT_APPROVE_REQUEST",
    MINT_APPROVE_SUCCESS: "MINT_APPROVE_SUCCESS",
    MINT_APPROVE_FAIL: "MINT_APPROVE_FAIL",
    MINT_APPROVE_PENDING: "MINT_APPROVE_PENDING",
  },
  CheckMintAllowance: {
    MINT_ALLOWANCE_REQUEST: "MINT_ALLOWANCE_REQUEST",
    MINT_ALLOWANCE_SUCCESS: "MINT_ALLOWANCE_SUCCESS",
    MINT_ALLOWANCE_FAIL: "MINT_ALLOWANCE_FAIL",
    MINT_ALLOWANCE_PENDING: "MINT_ALLOWANCE_PENDING",
  },
  MintToken: {
    MINT_TOKEN_REQUEST: "MINT_TOKEN_REQUEST",
    MINT_TOKEN_SUCCESS: "MINT_TOKEN_SUCCESS",
    MINT_TOKEN_FAIL: "MINT_TOKEN_FAIL",
    MINT_TOKEN_PENDING: "MINT_TOKEN_PENDING",
  },
  MintToToken: {
    MINT_TO_TOKEN_REQUEST: "MINT_TO_TOKEN_REQUEST",
    MINT_TO_TOKEN_SUCCESS: "MINT_TO_TOKEN_SUCCESS",
    MINT_TO_TOKEN_FAIL: "MINT_TO_TOKEN_FAIL",
    MINT_TO_TOKEN_PENDING: "MINT_TO_TOKEN_PENDING",
  },
  MintTokenETH: {
    MINT_ETH_REQUEST: "MINT_ETH_REQUEST",
    MINT_ETH_SUCCESS: "MINT_ETH_SUCCESS",
    MINT_ETH_FAIL: "MINT_ETH_FAIL",
    MINT_ETH_PENDING: "MINT_ETH_PENDING",
  },
  MintToTokenETH: {
    MINT_TO_ETH_REQUEST: "MINT_TO_ETH_REQUEST",
    MINT_TO_ETH_SUCCESS: "MINT_TO_ETH_SUCCESS",
    MINT_TO_ETH_FAIL: "MINT_TO_ETH_FAIL",
    MINT_TO_ETH_PENDING: "MINT_TO_ETH_PENDING",
  },
  BurnApprove: {
    BURN_APPROVE_REQUEST: "BURN_APPROVE_REQUEST",
    BURN_APPROVE_SUCCESS: "BURN_APPROVE_SUCCESS",
    BURN_APPROVE_FAIL: "BURN_APPROVE_FAIL",
    BURN_APPROVE_PENDING: "BURN_APPROVE_PENDING",
  },
  CheckBurnAllowance: {
    BURN_ALLOWANCE_REQUEST: "BURN_ALLOWANCE_REQUEST",
    BURN_ALLOWANCE_SUCCESS: "BURN_ALLOWANCE_SUCCESS",
    BURN_ALLOWANCE_FAIL: "BURN_ALLOWANCE_FAIL",
    BURN_ALLOWANCE_PENDING: "BURN_ALLOWANCE_PENDING",
  },
  BurnToken: {
    BURN_TOKEN_REQUEST: "BURN_TOKEN_REQUEST",
    BURN_TOKEN_SUCCESS: "BURN_TOKEN_SUCCESS",
    BURN_TOKEN_FAIL: "BURN_TOKEN_FAIL",
    BURN_TOKEN_PENDING: "BURN_TOKEN_PENDING",
  },
  BurnTokenETH: {
    BURN_ETH_REQUEST: "BURN_ETH_REQUEST",
    BURN_ETH_SUCCESS: "BURN_ETH_SUCCESS",
    BURN_ETH_FAIL: "BURN_ETH_FAIL",
    BURN_ETH_PENDING: "BURN_ETH_PENDING",
  },
  LockUI: {
    LOCK_UI_SUCCESS: "LOCK_UI_SUCCESS",
  },
  UnlockUI: {
    UNLOCK_UI_SUCCESS: "UNLOCK_UI_SUCCESS",
  },
  GetGETH: {
    GET_GETH_REQUEST: "GET_GETH_REQUEST",
    GET_GETH_SUCCESS: "GET_GETH_SUCCESS",
    GET_GETH_FAIL: "GET_GETH_FAIL",
    GET_GETH_PENDING: "GET_GETH_PENDING",
  },
  ClearGethStatus: {
    CLEAR_GETH_STATUS_SUCCESS: "CLEAR_GETH_STATUS_SUCCESS",
  },
};
